common:
  # 4개의 카메라 토픽을 리스트로 정의
  img_topics: 
    - "/alphasense/cam0/image_raw" # 앞 (Front)
    - "/alphasense/cam1/image_raw" # 오른쪽 (Right)
    - "/alphasense/cam2/image_raw" # 뒤 (Back)
    - "/alphasense/cam3/image_raw" # 왼쪽 (Left)
  lid_topic: "/hesai/pandar"
  imu_topic: "/alphasense/imu"
  num_of_cam: 4 # 카메라 개수 명시
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  # LiDAR to IMU Extrinsics (T_li)
  extrinsic_T: [-0.001, -0.00855, 0.055] 
  extrinsic_R: [0, -1, 0, -1, 0, 0, 0, 0, -1]
  
  # --- Camera to LiDAR Extrinsics (T_cl) ---
  # 각 카메라별로 R_cl과 P_cl을 정의합니다.
  # P_cl은 0벡터로, R_cl은 앞뒤좌우를 보도록 설정합니다.
  # (카메라 좌표계 z축이 광축, x축이 오른쪽, y축이 아래라고 가정)

  # Cam 0: Front (카메라 z축이 라이다 x축 방향)
  R_cl_0: [ 0,  0,  1,
           -1,  0,  0,
            0, -1,  0]
  P_cl_0: [0.0, 0.0, 0.0]

  # Cam 1: Right (카메라 z축이 라이다 y축 방향)
  R_cl_1: [ 1,  0,  0,
            0,  0,  1,
            0, -1,  0]
  P_cl_1: [0.0, 0.0, 0.0]

  # Cam 2: Back (카메라 z축이 라이다 -x축 방향)
  R_cl_2: [ 0,  0, -1,
            1,  0,  0,
            0, -1,  0]
  P_cl_2: [0.0, 0.0, 0.0]

  # Cam 3: Left (카메라 z축이 라이다 -y축 방향)
  R_cl_3: [-1,  0,  0,
            0,  0, -1,
            0,  1,  0]
  P_cl_3: [0.0, 0.0, 0.0]

time_offset:
  imu_time_offset: 0.0
  img_time_offset: 0.0
  exposure_time_init: 0.0

preprocess:
  hilti_en: true
  point_filter_num: 1
  filter_size_surf: 0.1 # 0.2
  lidar_type: 5 # HesaiXT32
  scan_line: 32
  blind: 0.6 # 0.1 0.3
 
vio:
  max_iterations: 5
  outlier_threshold: 500
  img_point_cov: 1000
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.5 # 0.1
  gyr_cov: 0.01
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0001 # 0.0025
  voxel_size: 0.4
  max_layer: 2
  max_points_num: 100
  layer_init_num: [5, 5, 5, 5, 5]

local_map:  
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: true
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "exp09_cupola"
  pose_output_en: true

pcd_save:
  pcd_save_en: false
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
